# Dependencies
markdown: kramdown
# markdown: redcarpet
rouge: pygments
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: ["jekyll-paginate"]

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Greg's Blog
description:      'Hello Welcome to Greg Blog!'
url:              https://github.com/GregNing
baseurl:          /
# Author
author:
  name: 'Greg'
  url: https://github.com/GregNing

paginate:         5
# tags
tag:
    jekyll: https://jekyllrb.com/

github:
  repo:  https://github.com/GregNing

sass:
    sass_dir: assets/stylesheets
    style: compressed
