# Dependencies
markdown            : kramdown
# markdown: redcarpet
redcarpet:
  extensions        : ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter         : rouge
plugins             : ["jekyll-paginate", "jekyll-assets", "jekyll-seo-tag"]

# Permalinks
permalink           : pretty

# Setup
title               : Greg's Blog
description         : 'Hello Welcome to Greg Blog!'
url                 : https://github.com/GregNing
baseurl             : /
# Author
author:
  name              : 'Greg'
  url               : https://github.com/GregNing

paginate            : 5
# tags
tag:
  jekyll            : https://jekyllrb.com/

github:
  repo              :  https://github.com/GregNing

sass:
  sass_dir          : assets/stylesheets
  style             : compressed

custom_css:
  - main
  - bootstrap.min
  - syntax

plugin_js:
  - jquery
  - jquery.pjax
  - prettify
  - default

disqus_name: greg-yang