# Dependencies
markdown: kramdown
# markdown: redcarpet
rouge: pygments
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Greg's Blog
description:      'Hello Welcome to Greg Blog!'
url:              https://github.com/GregNing
baseurl:          /
# Author
author:
  name: 'Greg'
  url: https://github.com/GregNing

paginate:         5
# tags
tag:
    jekyll: https://jekyllrb.com/

github:
  repo:  https://github.com/GregNing

sass:
    sass_dir: assets/stylesheets
    style: compressed

# assets:
#   caching:
#     path: ".jekyll-cache/assets/stylesheets"
#     type: file # Possible values: memory, file
#     enabled: true
#   compress:
#     css: true
#     js: true
#   sources:
#     # - _assets
#     - _assets/stylesheets/fonts
#     - _assets/stylesheets/font-awesome

plugins:
  - jekyll-assets
  - jekyll-paginate