# Dependencies
markdown:         kramdown
rouge:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Greg's Blog
description:      'Hello Welcome to Greg Blog!'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

github:
  repo:  https://github.com/GregNing

sass:
    sass_dir: _assets/stylesheets
    style: compressed

# assets:
#   caching:
#     path: ".jekyll-cache/assets/stylesheets"
#     type: file # Possible values: memory, file
#     enabled: true
#   compress:
#     css: true
#     js: true
#   sources:
#     # - _assets
#     - _assets/stylesheets/fonts
#     - _assets/stylesheets/font-awesome

plugins:
  - jekyll-assets
  - jekyll-paginate